apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-app
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
        - image: elasticsearch:7.16.2
          name: elasticsearch-app
          ports:
          - containerPort: 9200
          env:
          - name: ES_JAVA_OPTS
            value: "-Xmx256m -Xms256m"
          - name: discovery.type
            value: single-node
          - name: http.port
            value: "9200"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
  selector:
   app: elasticsearch-app
