apiVersion: apps/v1
kind: Deployment
metadata:
  name: financemanagementapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financemanagementapi-app
  template:
    metadata:
      labels:
        app: financemanagementapi-app
    spec:
      containers:
        - image: kvtim/financemanagementapi:latest
          name: financemanagementapi-app
          ports:
          - containerPort: 5002
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:5002"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: financemanagementapi-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 5002
  selector:
   app: financemanagementapi-app
