apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencymanagementapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencymanagementapi-app
  template:
    metadata:
      labels:
        app: currencymanagementapi-app
    spec:
      containers:
        - image: kvtim/currencymanagementapi:latest
          name: currencymanagementapi-app
          ports:
          - containerPort: 5001
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:5001"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: currencymanagementapi-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
   app: currencymanagementapi-app
