apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
        - image: rabbitmq:3.11-management
          name: rabbitmq-app
          ports:
          - containerPort: 5672
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    targetPort: 5672
  selector:
   app: rabbitmq-app
