apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementapi-app
  template:
    metadata:
      labels:
        app: usermanagementapi-app
    spec:
      containers:
        - image: kvtim/usermanagementapi:latest
          name: usermanagementapi-app
          ports:
          - containerPort: 5003
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:5003"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: usermanagementapi-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5003
  selector:
   app: usermanagementapi-app
